// Datos simulados con la misma estructura del backend real
// Se reemplazarán por llamadas al API cuando se conecte el backend

export const productosSimulados = [
  {
    id: "1",
    nombre: "Playera Oversize AURA",
    sku: "PLY-001",
    categoria: "Playeras",
    departamento: "Unisex",
    marca: "AURA",
    precioVenta: 249,
    stock: 15,
    imagen: null,
    inventario: [
      { talla: "S", stock: 3 },
      { talla: "M", stock: 7 },
      { talla: "L", stock: 5 },
    ],
  },
  {
    id: "2",
    nombre: "Blusa Satinada Elegance",
    sku: "BLU-001",
    categoria: "Blusas",
    departamento: "Dama",
    marca: "AURA",
    precioVenta: 399,
    stock: 8,
    imagen: null,
    inventario: [
      { talla: "XS", stock: 2 },
      { talla: "S",  stock: 4 },
      { talla: "M",  stock: 2 },
    ],
  },
  {
    id: "3",
    nombre: "Camisa Denim Vintage",
    sku: "CAM-001",
    categoria: "Camisas",
    departamento: "Caballero",
    marca: "AURA",
    precioVenta: 549,
    stock: 10,
    imagen: null,
    inventario: [
      { talla: "M",  stock: 4 },
      { talla: "L",  stock: 4 },
      { talla: "XL", stock: 2 },
    ],
  },
  {
    id: "4",
    nombre: "Suéter Trenzado Lila",
    sku: "SUE-001",
    categoria: "Suéteres",
    departamento: "Dama",
    marca: "AURA",
    precioVenta: 599,
    stock: 6,
    imagen: null,
    inventario: [
      { talla: "S", stock: 2 },
      { talla: "M", stock: 3 },
      { talla: "L", stock: 1 },
    ],
  },
  {
    id: "5",
    nombre: "Sudadera Hoodie Cropped",
    sku: "SUD-001",
    categoria: "Sudaderas",
    departamento: "Dama",
    marca: "AURA",
    precioVenta: 629,
    stock: 12,
    imagen: null,
    inventario: [
      { talla: "XS", stock: 3 },
      { talla: "S",  stock: 5 },
      { talla: "M",  stock: 4 },
    ],
  },
  {
    id: "6",
    nombre: "Chamarra Bomber Satinada",
    sku: "CHA-001",
    categoria: "Chamarras",
    departamento: "Unisex",
    marca: "AURA",
    precioVenta: 1099,
    stock: 5,
    imagen: null,
    inventario: [
      { talla: "S",  stock: 1 },
      { talla: "M",  stock: 2 },
      { talla: "L",  stock: 2 },
    ],
  },
  {
    id: "7",
    nombre: "Abrigo Oversized Clásico",
    sku: "ABR-001",
    categoria: "Abrigos",
    departamento: "Dama",
    marca: "AURA",
    precioVenta: 1299,
    stock: 4,
    imagen: null,
    inventario: [
      { talla: "S", stock: 1 },
      { talla: "M", stock: 2 },
      { talla: "L", stock: 1 },
    ],
  },
  {
    id: "8",
    nombre: "Vestido Slip Satinado",
    sku: "VES-001",
    categoria: "Vestidos",
    departamento: "Dama",
    marca: "AURA",
    precioVenta: 749,
    stock: 7,
    imagen: null,
    inventario: [
      { talla: "XS", stock: 2 },
      { talla: "S",  stock: 3 },
      { talla: "M",  stock: 2 },
    ],
  },
  {
    id: "9",
    nombre: "Falda Mini Plisada",
    sku: "FAL-001",
    categoria: "Faldas",
    departamento: "Dama",
    marca: "AURA",
    precioVenta: 449,
    stock: 9,
    imagen: null,
    inventario: [
      { talla: "24", stock: 3 },
      { talla: "26", stock: 4 },
      { talla: "28", stock: 2 },
    ],
  },
  {
    id: "10",
    nombre: "Shorts Deportivo Ribbed",
    sku: "SHO-001",
    categoria: "Shorts",
    departamento: "Unisex",
    marca: "AURA",
    precioVenta: 299,
    stock: 0,
    imagen: null,
    inventario: [],
  },
  {
    id: "11",
    nombre: "Pantalón Cargo Wide-Leg",
    sku: "PAN-001",
    categoria: "Pantalones",
    departamento: "Unisex",
    marca: "AURA",
    precioVenta: 549,
    stock: 11,
    imagen: null,
    inventario: [
      { talla: "26", stock: 3 },
      { talla: "28", stock: 5 },
      { talla: "30", stock: 3 },
    ],
  },
  {
    id: "12",
    nombre: "Tenis Urban Chunky",
    sku: "CAL-001",
    categoria: "Calzado",
    departamento: "Unisex",
    marca: "AURA",
    precioVenta: 899,
    stock: 8,
    imagen: null,
    inventario: [
      { talla: "25",   stock: 2 },
      { talla: "26",   stock: 3 },
      { talla: "27",   stock: 3 },
    ],
  },
  {
    id: "13",
    nombre: "Bolsa Crossbody Mini",
    sku: "ACC-001",
    categoria: "Accesorios",
    departamento: "Dama",
    marca: "AURA",
    precioVenta: 429,
    stock: 14,
    imagen: null,
    inventario: [
      { talla: "Unitalla", stock: 14 },
    ],
  },
  {
    id: "14",
    nombre: "Gorra Clásica Bordada",
    sku: "ACC-002",
    categoria: "Accesorios",
    departamento: "Unisex",
    marca: "AURA",
    precioVenta: 159,
    stock: 20,
    imagen: null,
    inventario: [
      { talla: "Unitalla", stock: 20 },
    ],
  },
];
